package com.babakan.cashier.utils.constant

object RemoteData {
    const val COLLECTION_USERS = "users"
    const val COLLECTION_PRODUCT = "products"
    const val COLLECTION_CATEGORY = "categories"
    const val COLLECTION_CART = "cart"
    const val COLLECTION_TRANSACTIONS = "transactions"
    const val COLLECTION_PRODUCT_OUT = "productOut"

    const val FIELD_ID = "id"
    const val FIELD_USER_ID = "userId"
    const val FIELD_PRODUCT_ID = "productId"
    const val FIELD_CATEGORY_ID = "categoryId"
    const val FIELD_TRANSACTION_ID = "transactionId"
    const val FIELD_CREATED_AT = "_createdAt"
    const val FIELD_UPDATE_AT = "_updateAt"
    const val FIELD_NAME = "name"
    const val FIELD_USERNAME = "username"
    const val FIELD_EMAIL = "email"
    const val FIELD_IS_OWNER = "isOwner"
    const val FIELD_IS_ACTIVE = "isActive"
    const val FIELD_IMAGE_URL = "imageUrl"
    const val FIELD_ICON_URL = "iconUrl"
    const val FIELD_PRODUCT_OUT = "productOut"
    const val FIELD_PRODUCT = "product"
    const val FIELD_CATEGORY = "category"
    const val FIELD_QUANTITY = "quantity"
    const val FIELD_PRICE = "price"
    const val FIELD_TOTAL_PRICE = "totalPrice"
    const val FIELD_CUSTOMER_NAME = "customerName"
    const val FIELD_TABLE_NUMBER = "tableNumber"
    const val FIELD_NOTES = "notes"
}